default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'prog-image-api_development' %>
  username: <%= ENV['DB_USER'] || ENV['USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'prog-image-api_development' %>

test:
  <<: *default
  database: prog-image-api_test

production:
  <<: *default
  database: prog-image-api_production
  url: <%= ENV['DATABASE_URL'] %>
